### ISSUE TITLE
Set Up Kanban Board

### ISSUE THREAD

**Issue by angeluray** [Mov305/moviesC2#21]
# Hi good reviewer

This is the link of our Github Project:

https://github.com/users/Mov305/projects/3

We're currently working in a group of 2.

**Comment by Omar-Muhamad** [comment]
# Changes Required ♻️
### Hi @angeluray and @Mov305,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)


## (Changes Required) Aspects to improve: ♻️

- [ ] Please assign all tasks to a particular group member and for group tasks assign both of you or at least one of you regarding the equal amount of work shared. and for individual tasks assign one of you for student A tasks and the other for student B tasks.

![image](https://user-images.githubusercontent.com/68796232/187289602-67cc332d-7b60-4857-9f8e-04a1fca51fe3.png)

when the task is assigned it will look like that

![image](https://user-images.githubusercontent.com/68796232/187283656-96cec6a4-c352-44e0-8fff-a59b5e622aca.png)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
